### ISSUE TITLE
PERL_DL_NONLAZY isn't set for UNIX

### ISSUE THREAD

**Issue by XSven** [briandfoy/test-manifest#16]
`ExtUtils::MM_Unix` overrides [test_via_harness](https://metacpan.org/dist/ExtUtils-MakeMaker/source/lib/ExtUtils/MM_Unix.pm#L3866). This leads to

> PERL_DL_NONLAZY=1 $(FULLPERLRUN) "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness($(TEST_VERBOSE), '$(INST_LIB)', '$(INST_ARCHLIB)')" $(TEST_FILES)

If `Test::Manifest` is active the command looks like

> $(FULLPERLRUN) "-MTest::Manifest" "-e" "run_t_manifest($(TEST_VERBOSE), '$(INST_LIB)', '$(INST_ARCHLIB)', $(TEST_LEVEL) )"

Why is the setup of PERL_DL_NONLAZY not needed anymore?

**Comment by briandfoy** [comment]
This module is pure Perl, so `PERL_DL_NONLAZY` doesn't help anything. It probably doesn't help anything in the MM_Unix example either.

From [perlrun](https://perldoc.perl.org/perlrun) on `PERL_DL_NONLAZY`:

> Set to "1" to have Perl resolve all undefined symbols when it loads a dynamic library. The default behaviour is to resolve symbols when they are used. Setting this variable is useful during testing of extensions, as it ensures that you get an error on misspelled function names even if the test suite doesn't call them.

If you're think you are experiencing unexpected behavior because of this, try sticking the `PERL_DL_NONLAZY=1` in front of the Test::Manifest bit in the *Makefile* to see if the problem goes away. If there is no problem, or the problem doesn't disappear, this is likely not a problem. If you have a problem and adding the `PERL_DL_NONLAZY=1` fixes it, we can re-open this issue. In that case, please supply as much information as you can.
